### ISSUE TITLE
Add skin commands

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWLHelper#7]
It'd be nice if you could have the ability to pull up pages from https://skins.ds-homebrew.com
For example:
`.skins unlaunch` - links to https://skins.ds-homebrew.com/unlaunch
`.skins dsi windows 95` - links to the skin if found, in this case https://skins.ds-homebrew.com/nintendo-dsi/windows-95

Also, might wanna fix your issue templates.

**Comment by lifehackerhansol** [comment]
Yeah the issue templates are a relic of Kurisu since I low-key copied the flake8 check script (as well as uh everything else in `.github` lol

For the issue itself, the first one seems trivial. The second one... I could try. Will have to see.

**Comment by Epicpkmn11** [comment]
Might be able to use the UniStore file to make this relatively easy since that's just a JSON, that might be missing some important things though so could also just have it output a proper JSON like Universal-DB does.

https://raw.githubusercontent.com/DS-Homebrew/twlmenu-extras/master/unistore/twlmenu-skins.unistore

**Comment by lifehackerhansol** [comment]
I guess if we implemented unistore reads, it'd read the "console" section, then move to the name of the skin.

I have no idea if I can make it in that sequence as the unistore file has it backwards, but eh.
